version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - node-backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    command: npm start

  python-backend:
    build:
      context: ./backend/python-backend
      dockerfile: Dockerfile.python
    ports:
      - "5001:5001"
  node-backend:
    build:
      context: ./backend/node-backend
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"
    depends_on:
      - python-backend
      - mongodb
    environment:
      - MONGO_URL=mongodb://localhost:27017/finance-assistant

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
